apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    uid: prometheus
    orgId: 1
    url: http://prometheus:9090
    access: proxy
    isDefault: true
    editable: true

  - name: Jaeger
    type: jaeger
    uid: jaeger
    orgId: 1
    url: http://jaeger:16686
    access: proxy
    editable: true
